name: Java CI with MySQL

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: Mysql123
          MYSQL_DATABASE: testdb
        ports:
          - 3307:3306
        options: >-
          --health-cmd="mysqladmin ping --silent --user=root --password=Mysql123"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tests
        env:
          DB_URL: jdbc:mysql://localhost:3307/testdb
          DB_USERNAME: root
          DB_PASSWORD: Mysql123
        run: mvn clean verify
