name: Integration Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: testdb
          MYSQL_ROOT_PASSWORD: Mysql123
        ports:
          - 3307:3306
        options: >-
          --health-cmd="mysqladmin ping --silent --user=root --password=Mysql123" #health-cmd
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Wait for MySQL to be ready
        run: |
          for i in {1..30}; do
            nc -z localhost 3307 && echo "MySQL is up" && break || (
              echo "Waiting for MySQL..." && sleep 2
            )
          done
          if ! nc -z localhost 3307; then
            echo "MySQL did not become ready in time. Exiting."
            exit 1
          fi

      - name: Run tests
        run: mvn clean verify
        env:
          DB_URL: jdbc:mysql://localhost:3306/testdb
          DB_USERNAME: root
          DB_PASSWORD: Mysql123


